### PR TITLE
Refactored documentation styles to not use Twitter Bootstrap CSS, but own, lightweight and visually same stylesheet

### PR DESCRIPTION
**Pull request by DaveBitter**
I refactored documentation styles to not use Twitter Bootstrap CSS, but own, lightweight and visually same stylesheet.

In the future, we might want to make a more visually appealing default style than we currently have.

### CODE REVIEW

**Comment by Timvdv** [comment]
This is great! I was getting the Bootstrap file in showing up in my searches all the time, super annoying.

Bit nit-picky but the spacing in the overview can be bigger (see image).

Screenshot 2019-09-08 at 17 42 07

**Comment by waarissyb** [comment]
> Bit nit-picky but the spacing in the overview can be bigger (see image).
Some other margins are off as well. And the `font-size` of the code sample

**Comment by DaveBitter** [comment]
I noticed that in three different projects of mine the spacings were all different :p. Should we just take on that looks good?

@waarissyb what do you mean with the embedded styles?

**Comment by DaveBitter** [comment]
Can we merge then?

**Pull request merged**
