### PR TITLE
Add quality badges to README

### PR DESCRIPTION
**Pull request by lstanisavljevic**
Add badges to let us keep an eye on outdated dependencies, test coverage and dependency vulnerabilities.

### CODE REVIEW

**Comment by lstanisavljevic** [comment]
> I know this is very nitpick-y but I would prefer it if unrelated codestyle changes weren't part of the PR.

Well I think changes in other files arrived from rebasing with another PR, to avoid later conflicts

**Comment by lstanisavljevic** [comment]
Pardon, those changes actually don't have anything to do with any other PR, they were made by pre-commit githook, and when I try reverting them, the same githook re-applies them. So what do we do? And does it mean we don't have same pre-commit settings across the guild?

**Comment by mdecorte** [comment]
The [coverage one](https://coveralls.io/repos/github/mirabeau-nl/frontend-boilerplate/badge.svg?branch=master) Doesn't seem to do much

**Comment by lstanisavljevic** [comment]
> The [coverage one](https://coveralls.io/repos/github/mirabeau-nl/frontend-boilerplate/badge.svg?branch=master) Doesn't seem to do much

Of course it doesn't, it's because we are not covered :)

**Comment by mdecorte** [comment]
> > The [coverage one](https://coveralls.io/repos/github/mirabeau-nl/frontend-boilerplate/badge.svg?branch=master) Doesn't seem to do much
> 
> Of course it doesn't, it's because we are not covered :)

😂 okayy. Fair enough. So did anyone decide on using this tool? Vs what alternatives there are on the market?

**Comment by lstanisavljevic** [comment]
> > > The [coverage one](https://coveralls.io/repos/github/mirabeau-nl/frontend-boilerplate/badge.svg?branch=master) Doesn't seem to do much
> > 
> > 
> > Of course it doesn't, it's because we are not covered :)
> 
> 😂 okayy. Fair enough. So did anyone decide on using this tool? Vs what alternatives there are on the market?

No one explicitly decided on this particular tool, it's used on the example given in this Trello ticket https://trello.com/c/T8qrdLr7/79-add-dependencies-up-to-date-badge

From what I can see, the main competition to Coveralls is Codecov, however it seems that Coveralls is more widely used (https://stackshare.io/stackups/codecov-vs-coveralls), so it's likely to have better community support and all.

But we can easily change that on guild day, there's no such thing as Saint Coveralls :)

**Pull request merged**
