### PR TITLE
Add logo, update documentation

### PR DESCRIPTION
**Pull request by nienkedekker**
## What's this?
I updated the documentation.

I've added a logo to the boilerplate. It's a pretty quick Sketch, so I would appreciate feedback. Feel free to download the SVG and play around with it if you have better ideas! I've followed the Mirabeau guidelines regarding colors and thin lines.

I've also added a bunch of emojis to the headers in our readme. I think they make our readme a bit more fun and readable. It's a bit of a trend, see also:

* https://github.com/parcel-bundler/parcel
* https://github.com/yarnpkg/yarn
* https://github.com/drcmda/react-spring

### CODE REVIEW

**Comment by nienkedekker** [comment]
@waarissyb, I would appreciate your feedback on the logo I whipped up!

**Comment by swiv98** [comment]
I think the logo cannot be used like this. 
Apart from the funky alignment of the title with respect to the logo (non-designer opinion alert) , it also uses a direct reference to the Brando Sans font. Which will not display (correctly) if you don't have it installed. 
Include it as outlines, not as text, if we want the rest of the world to enjoy the logo ;-)

**Comment by nienkedekker** [comment]
@swiv81 ah yes of course! I can convert it into a png. I am hoping Syb can give some feedback on the logo, I’m sure we can make a nice one without having to bother a designer 💪

**Comment by nienkedekker** [comment]
@colin-aarts you have a point there 😋anyone I can try to reach out to, except maybe Mariella?

**Comment by colin-aarts** [comment]
@waarissyb: the fact that emoji are rendered differently in different contexts shouldn't be an objection in and of itself in my opinion; no one can be expected to know the gazillion possible renderings of any given emoji and it shouldn't matter as they will always roughly convey the same meaning — especially so when they are merely used as an enhancement in addition to a textual description.

**Comment by waarissyb** [comment]
Bon!

**Comment by branneman** [comment]
@nienkedekker If you squash the commits I'll merge it.

**Comment by nienkedekker** [comment]
@branneman: done!

**Pull request merged**
